server:
  port: 28088

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: chany
    password: chany1234


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true


chany:
  key: chany1234

  kakao:
    auth-redirect-url: http://localhost:28088/auth/kakao/callback
    auth-request-url: https://kauth.kakao.com/oauth/token
    client-id: 0b574c03d54a84e92c553163fef5b367
    profile-request-url: https://kapi.kakao.com/v2/user/me